package ramlContractValidator.writer;

import org.apache.maven.plugin.logging.Log;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 * Created by shendrickson1 on 6/25/14.
 *
 */
public class RamlWriter {

    private File templateFile;
    private String templateFileName = "RAML-Template-File.raml";
    private Log logger;

    public RamlWriter(String writeLocation, Log logger) {
        logger.info("RAML Template at: " + writeLocation + "/" + templateFileName);

        templateFile = new File(writeLocation, templateFileName);
        this.logger = logger;
    }

    public void write(String dump) {
        FileWriter fw = null;
        try {
            templateFile.createNewFile();
            fw = new FileWriter(templateFile);
        } catch (IOException e) {
            throw new RuntimeException("Could not access template file");
        }

        try {
            fw.write("# TEMPLATE RAML GENERATED BY THE RAML CONTRACT VALIDATOR\n");
            fw.write("#     THIS RAML SHOULD BE FILLED OUT ACCORDING TO RAML SPEC FOUND AT: https://github.com/raml-org/raml-spec\n");
            fw.write("#     THESE LINES MUST BE DELETED BEFORE THIS FILE IS CONSIDERED TO BE VALID RAML\n");
            fw.write("#     Have a fantastic day. \n");
            fw.write("#     -Services Team\n");
            fw.write("#\n");
            fw.write(dump);
            fw.flush();
            fw.close();
        } catch (IOException e) {
            throw new RuntimeException("Could not write to template file");
        }
    }
}
